server:
  port: 8070
spring:
  application:
    name: shipments-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shipments_db?useSSL=false&serverTimezone=UTC
    username: root
    password: mauriciochacon
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    function:
      definition: userCreatedEvent;userUpdatedEvent;profileCreatedEvent
    stream:
      bindings:
        userCreatedEvent-in-0:
          destination: user-events
          content-type: application/json
          group: shipments-service-group
          binder: rabbit
        userUpdatedEvent-in-0:
          destination: user-update-events
          content-type: application/json
          group: shipments-service-group
          binder: rabbit
        profileCreatedEvent-in-0:
          destination: profile-events
          content-type: application/json
          group: shipments-service-group
          binder: rabbit
        shipmentCreatedEvent-out-0:
          destination: shipment-events
          content-type: application/json
          binder: rabbit
        shipmentUpdatedEvent-out-0:
          destination: shipment-update-events
          content-type: application/json
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      rabbit:
        bindings:
          userCreatedEvent-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 60000
              requeue-rejected: false
          userUpdatedEvent-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 60000
              requeue-rejected: false
          profileCreatedEvent-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 60000
              requeue-rejected: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/