server:
  port: 9090

spring:
  application:
    name: profiles-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/profiles_db?useSSL=false&serverTimezone=UTC
    username: root
    password: mauriciochacon
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: com.profiles.service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    function:
      definition: userCreated
    stream:
      bindings:
        userCreated-in-0:
          destination: user-events
          content-type: application/json
          group: profiles-service-group
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/