server:
  port: 8086

spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:mysql://localhost:3306/payments_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.payments.service.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payments-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

paypal:
  client-id: ${PAYPAL_CLIENT_ID:AV-cxvG7fkey7BID_IFyb9Kc6QVvnJpjKGMWXXHwpRIA_Isylj0dwrfnBavKgLKtn96tiKQzDY9ztrug}
  client-secret: ${PAYPAL_CLIENT_SECRET:ECFGoKRAwEcz7p3VqC9koQgBmsqtEaO0hbEvMU8UIgemTTnQa0pP1aI6CdTzKU55k8wrMRcTcJ2HPH-G}
  mode: ${PAYPAL_MODE:sandbox}
  webhook-id: ${PAYPAL_WEBHOOK_ID:http://127.0.0.1:4040 }

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.payments.service: DEBUG
    org.springframework.kafka: INFO
